# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        ('mentorships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdegree',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Program'),
        ),
        migrations.AddField(
            model_name='userdegree',
            name='study_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.StudyYear'),
        ),
        migrations.AddField(
            model_name='userdegree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorships.UserUniversity'),
        ),
        migrations.AddField(
            model_name='universitysession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorships.Session'),
        ),
        migrations.AddField(
            model_name='universitysession',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Method'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='university_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorships.UniversitySession'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('university_session', 'mentee')]),
        ),
    ]
