# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 14:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorships', '0002_auto_20180208_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('organiser', 'Organiser'), ('other', 'Other')], max_length=16, verbose_name='Role')),
                ('university_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorships.UniversitySession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='gender_mode',
            field=models.CharField(blank=True, choices=[('strict', 'It IS important to me to be matched to the same gender.'), ('optional', 'If possible, match me to the same gender but not essential.'), ('na', 'It IS NOT important to me which gender I am matched with.')], help_text='Note that if you would like to be matched to the same gender, you must select an option from the following field.', max_length=16, verbose_name='Gender Mode'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='hear_about',
            field=models.TextField(null=True, verbose_name='How did you hear about this program?'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='mentee_number',
            field=models.PositiveSmallIntegerField(default=0, help_text="Number of mentees you'd be willing to support (max is 3).", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='uni_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='University ID'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='why_diversity',
            field=models.TextField(null=True, verbose_name='Why do you think diversity, equity and inclusion in STEM are important?'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='why_mentor',
            field=models.TextField(null=True, verbose_name='Why do you want to become a mentor?'),
        ),
    ]
