# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project.apps.mentorships.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0003_auto_20180209_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysession',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdegree',
            name='major',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useruniversity',
            name='intended_study',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Intended/Preferred Subject Area'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorships.UserUniversity'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='gender_mode',
            field=models.CharField(blank=True, choices=[('strict', 'Definitely'), ('optional', 'If possible'), ('na', 'Unconcerned')], help_text='Note that if you would like to be matched to the same gender, you must select an option from the following field.', max_length=16, verbose_name='Gender Mode'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='hear_about',
            field=models.TextField(blank=True, null=True, verbose_name='How did you hear about this program?'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='method_preferences',
            field=models.ManyToManyField(to='universities.Method', verbose_name='What will be your medium of interaction in the program?'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='uni_id',
            field=models.CharField(max_length=64, unique=True, validators=[project.apps.mentorships.validators.validate_uni_id], verbose_name='University ID'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='why_diversity',
            field=models.TextField(blank=True, null=True, verbose_name='Why do you think diversity, equity and inclusion in STEM are important?'),
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='why_mentor',
            field=models.TextField(blank=True, null=True, verbose_name='Why do you want to become a mentor?'),
        ),
    ]
