# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0005_auto_20180210_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='notes',
            field=models.CharField(default='', help_text='Further information if necessary.', max_length=1024, verbose_name='Notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useruniversity',
            name='gender_mode',
            field=models.CharField(blank=True, choices=[('strict', 'Definitely'), ('optional', 'If possible'), ('na', 'Unconcerned')], max_length=16, verbose_name='Gender Mode'),
        ),
    ]
