# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0006_auto_20180210_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdegree',
            options={'ordering': ('-major',)},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ('university_session', 'is_active', 'user__user__gender')},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Further information if necessary.', max_length=1024, verbose_name='Notes'),
        ),
    ]
