# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20180209_0236'),
        ('mentorships', '0008_auto_20180211_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useruniversity',
            options={'ordering': ('degree_major',), 'verbose_name_plural': 'university users'},
        ),
        migrations.AddField(
            model_name='useruniversity',
            name='degree_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.Program'),
        ),
    ]
