# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0009_auto_20180224_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniversity',
            name='is_current_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useruniversity',
            name='is_current_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
