# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, max_length=512, verbose_name='Interests, hobbies or sports'),
        ),
    ]
