# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Master, Bachelor', max_length=255, verbose_name='Full Name')),
                ('abbreviation', models.CharField(blank=True, max_length=32, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Science, Computing, Clinical Psychology, BiologicalScience (Advanced)', max_length=255, verbose_name='Full Name')),
                ('abbreviation', models.CharField(blank=True, max_length=32, verbose_name='Abbreviation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_STEMM', models.BooleanField(default=True, verbose_name='Is STEMM eligible')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('abbreviation', models.CharField(blank=True, max_length=32, verbose_name='Abbreviation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_STEMM', models.BooleanField(default=True, verbose_name='Is STEMM eligible')),
                ('full_name', models.CharField(blank=True, default='', help_text='Science, Computing, Clinical Psychology, BiologicalScience (Advanced)', max_length=255, verbose_name='Full Name')),
                ('abbreviation', models.CharField(blank=True, max_length=32, verbose_name='Abbreviation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Cycle')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Degree')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.CharField(max_length=3, verbose_name='Year of Study (number)')),
                ('reference', models.CharField(help_text="Human readable version of year of study, eg 'First Year, Final Year'", max_length=128, verbose_name='Year of Study')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('abbreviation', models.CharField(max_length=32, verbose_name='Abbreviation')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
